### ISSUE TITLE
Can't resolve 'moment-timezone'

### ISSUE THREAD

**Issue by mikecbone** [pvoznyuk/react-live-clock#64]
Getting the error

```
./node_modules/react-live-clock/lib/Component.js
Module not found: Can't resolve 'moment-timezone' in '[...]/node_modules/react-live-clock/lib'
```

with 
```
"react-live-clock": "^5.0.9",
```

**Comment by anthony0030** [comment]
moment-timezone is a peer dep do you have it installed in your repo?

**Comment by mikecbone** [comment]
I wasn't sure as the npm page for react-live-clock shows `dependencies: none`, but if I install it I then get a different error

```
TypeError: s.tz is not a function
node_modules/react-moment/dist/index.js:22
```

**Comment by anthony0030** [comment]
I see now the confusion, there are peer dependencies, that's why they aren't showing up on the NPM page.
yarn or npm should be giving you a warning that they aren't installed. The complete list of peer deps are as follows:

moment
moment-timezone
react
react-moment

Please verify all are installed in your project. I will try to get back to you as soon as I can.

**Comment by mikecbone** [comment]
Right okay, my bad, that makes sense. 

I have
```
"moment": "^2.24.0",
"moment-timezone": "^0.5.31",
"react": "latest",
"react-moment": "^0.9.6",
```

For context, I was on `"react-live-clock": "^4.0.5"`, then I updated to 5 and this issue started. I already had moment and react-moment installed so only had to add (as discussed) moment-timezone

**Comment by anthony0030** [comment]
could you please send a snipped of code how you are using it or mak a code pen?

**Comment by mikecbone** [comment]
Hmm, I created a codesandbox but it works fine so I'm not sure what the difference is that's causing the issue (as I have quite a large project). 

I have noticed though that it's the timezone property, i.e. `timezone={'America/New_York'}`, that gives the error:
```
TypeError: s.tz is not a function
node_modules/react-moment/dist/index.js:22
```

I need to do some more digging

**Comment by mikecbone** [comment]
Okay, I'm confident at this point that it's a personal setup problem so I am going to drop the react-live-clock version to 4.0.5 as this doesn't depend on moment-timezone and be done. 

I wanted to use the `ticking={false}` but this doesn't work on 4.0.5 so I am going to use CSS to stop displaying the clock instead.

**Comment by anthony0030** [comment]
If you would like I can help you resolve this or help you find a better solution.

**Comment by Anantgaur** [comment]
Hello @anthony0030 . I just started a new project and wanted to use your package, I am getting the same error as OP on a fresh react project. 

I took a look and it looks like you changed the dependencies to peerDependencies and that made the project not download them. Even npm shows no dependencies when you look at the npm page. I have put in a pull request to change it but I am not sure why it was changed in the first place or if it's the correct way to do it. 

Manually installing those packages works. In the downloaded module, there is no peerDependencies or dependecies in package.json and all of the packages are in devDependencies. 

For now I downloaded 4.0.5 and that works but v5 doesn't at all. The dependencies were gone on the first beta version itself, I can also see that the downloads dropped from 18k to 4k after that release. 

It should be a simple fix of updating package.json. Thanks

**Comment by anthony0030** [comment]
NPM version 4 removed automatic peer dependency installation. NPM version 7 would fix this. You can check the version you are using with ```npm -v``` You might need to update the node version.
You can manually install the peer dependencies or update NPM.

**Comment by cjbland** [comment]
@mikecbone do you remember what you did to solve this? We just updated our dependencies and are now running into this with all of the necessary peer dependencies installed.

**Comment by anthony0030** [comment]
Could you please provide me with your package.json and a minimum and a minimum example of how you are using it?

**Comment by cjbland** [comment]
This is minimally what we are using: https://codesandbox.io/embed/modern-paper-1b9gdo?fontsize=14&hidenavigation=1&theme=dark

But our repo is huge and there was a dependency of a dependency that was causing the issues. We ended up having to upgrade both `react-live-clock` and `react-moment` to get past the issue.

**Comment by anthony0030** [comment]
So the issues are resolved now?

**Comment by cjbland** [comment]
> So the issues are resolved now?

Yes, by upgrading to `react-live-clock@5.7.0` and `react-moment@1.1.2`.
